version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'my_food'
      MYSQL_USER: 'myfood'
      MYSQL_PASSWORD: 'myfood'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
