
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/my_food
  username: myfood
  password: myfood
 jpa:
  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect